services:
  - type: web
    name: soporte-colegio
    runtime: dotnet
    plan: free
    buildCommand: dotnet publish -c Release -o publish
    startCommand: dotnet ./publish/SoporteColegio.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT
