// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoporteColegio.Data;

#nullable disable

namespace SoporteColegio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260923175532_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SoporteColegio.Models.FallaComun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Equipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FallasComunes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "No da imagen / Pantalla azul",
                            Equipo = "Proyector"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "No enciende",
                            Equipo = "Proyector"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "No enciende / No da video",
                            Equipo = "PC"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "No tiene internet",
                            Equipo = "PC"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "No responde el cursor o teclas",
                            Equipo = "Mouse/Teclado"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "No se escucha el audio",
                            Equipo = "Parlantes"
                        });
                });

            modelBuilder.Entity("SoporteColegio.Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Laboratorio 1"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Sala 4B"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Biblioteca"
                        });
                });

            modelBuilder.Entity("SoporteColegio.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetalleAdicional")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FallaComunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FallaComunId");

                    b.HasIndex("SalaId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("SoporteColegio.Models.Ticket", b =>
                {
                    b.HasOne("SoporteColegio.Models.FallaComun", "FallaComun")
                        .WithMany()
                        .HasForeignKey("FallaComunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoporteColegio.Models.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FallaComun");

                    b.Navigation("Sala");
                });
#pragma warning restore 612, 618
        }
    }
}
