// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoporteColegio.Data;

#nullable disable

namespace SoporteColegio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SoporteColegio.Models.FallaComun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Equipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FallasComunes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "No da imagen / Pantalla azul",
                            Equipo = "Proyector"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "No enciende",
                            Equipo = "Proyector"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "No enciende / No da video",
                            Equipo = "PC"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "No tiene internet",
                            Equipo = "PC"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "No responde el cursor o teclas",
                            Equipo = "Mouse/Teclado"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "No se escucha el audio",
                            Equipo = "Parlantes"
                        });
                });

            modelBuilder.Entity("SoporteColegio.Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Sala 1"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Sala 2"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Sala 3"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Sala 4"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Sala 5"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Sala 6"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Sala 7"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Sala 8"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Sala 9"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Sala 10"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Sala 11"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Sala 12"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Sala 13"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Sala 14"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Sala 15"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Sala 16"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Sala 17"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Sala 18"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Sala 19"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Sala 20"
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Sala 21"
                        },
                        new
                        {
                            Id = 22,
                            Nombre = "Sala 22"
                        },
                        new
                        {
                            Id = 23,
                            Nombre = "Sala 23"
                        },
                        new
                        {
                            Id = 24,
                            Nombre = "Sala 24"
                        },
                        new
                        {
                            Id = 25,
                            Nombre = "Sala 25"
                        },
                        new
                        {
                            Id = 26,
                            Nombre = "Sala 26"
                        },
                        new
                        {
                            Id = 27,
                            Nombre = "Sala 27"
                        },
                        new
                        {
                            Id = 28,
                            Nombre = "Sala 28"
                        },
                        new
                        {
                            Id = 29,
                            Nombre = "Sala 29"
                        },
                        new
                        {
                            Id = 30,
                            Nombre = "Sala 30"
                        },
                        new
                        {
                            Id = 31,
                            Nombre = "Sala 31"
                        },
                        new
                        {
                            Id = 32,
                            Nombre = "Sala 32"
                        },
                        new
                        {
                            Id = 33,
                            Nombre = "Sala de Computacion"
                        },
                        new
                        {
                            Id = 34,
                            Nombre = "Inspectoría"
                        },
                        new
                        {
                            Id = 35,
                            Nombre = "Oficina de UTP"
                        },
                        new
                        {
                            Id = 36,
                            Nombre = "Oficina PIE"
                        });
                });

            modelBuilder.Entity("SoporteColegio.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetalleAdicional")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FallaComunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FallaComunId");

                    b.HasIndex("SalaId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("SoporteColegio.Models.Ticket", b =>
                {
                    b.HasOne("SoporteColegio.Models.FallaComun", "FallaComun")
                        .WithMany()
                        .HasForeignKey("FallaComunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoporteColegio.Models.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FallaComun");

                    b.Navigation("Sala");
                });
#pragma warning restore 612, 618
        }
    }
}
